class_name DataClasses

enum SpawnHeight { HIGH_ONLY, MED_ONLY, LOW_ONLY, HIGH_MED, HIGH_LOW, MED_LOW, ANY, GROUND_ONLY }

enum Boss { BIG_BIRD, BANJO_FISH, ICE_PRINCE }

enum Enemies { OUR_GUY, MISBEEHAVE, PATHED_MISBEEHAVE, GUNNERFLY, SNEAKY_SNAKE, BRO_BUN, BRO_BEAR }